### ISSUE TITLE
Version 2.1 is incompatible with PHP 7.4 in Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by tehplague** [Ocramius/PackageVersions#167]
Due to the version constraint set to `^7.4.7`, this package's 2.1.x release (last one that is designated for PHP 7.4) is current incompatible with PHP 7.4 as shipped with Ubuntu 20.04 (most recent LTS version). Is there any reason why the dependency was set to a specific PHP patch release, e.g. a known bug in 7.4.0-7.4.6? Or would you be able to relieve the dependency to `^7.4` ?

Installing 3rd-party PHP packages - we all know deb.sury.org - in higher versions would technically work, but sometimes is not possible for various reasons.

**Comment by Ocramius** [comment]
Heyo, this is correct, since 7.4.6 is botched (broken `yield from`), and 7.4.1 broke compat on typed properties.

Therefore, it is indeed intentional to move to `^7.4.7` for the sake of stability.

 > Installing 3rd-party PHP packages - we all know deb.sury.org - in higher versions would technically work, but sometimes is not possible for various reasons.

That's something you need to bring up with whoever manages your production environment: in this year and time, running the distro PHP release is anachronistic, given that you can containerize it, run nix, compile and run it manually, etc, and it will also likely not match the version you run in CI unless you containerize the exact LTS distro too.

Use the constraint I've set as leverage to get your team to upgrade to `7.4.7` or newer (including `~8.0.0`)
